import { useState } from "react";
import { useAdmin } from "../context/AdminContext";

const emptyBanner = { eyebrow: "", title: "", description: "", cta: "Ver más", image: "", alt: "", path: "/" };

export default function Banners() {
  const { banners, saveBanner, deleteBanner } = useAdmin();
  const [editing, setEditing] = useState(null);
  const submit = (event) => { event.preventDefault(); saveBanner(editing); setEditing(null); };
  const readImage = (file) => { if (!file) return; const reader = new FileReader(); reader.onload = () => setEditing((value) => ({ ...value, image: reader.result })); reader.readAsDataURL(file); };
  return <section className="admin-page"><header className="admin-page__header"><div><p className="admin-kicker">PÁGINA DE INICIO</p><h1>Banners</h1><p>Controla las imágenes y mensajes de la portada.</p></div><button className="admin-button" onClick={() => setEditing(emptyBanner)}>＋ Nuevo banner</button></header>
    {banners.length ? <div className="admin-banner-grid">{banners.map((slide, index) => <article className="admin-banner-card" key={slide.id}><div className="admin-banner-card__image"><img src={slide.image} alt={slide.alt} /><span>Banner {index + 1}</span></div><div className="admin-banner-card__body"><small>{slide.eyebrow}</small><h2>{slide.title}</h2><p>{slide.description}</p><div><button onClick={() => setEditing({ ...slide })}>Editar</button><button className="danger" onClick={() => window.confirm("¿Eliminar este banner?") && deleteBanner(slide.id)}>Eliminar</button></div></div></article>)}</div> : <div className="admin-empty"><strong>No hay banners todavía</strong><p>Usa “Nuevo banner” para agregar el primero.</p></div>}
    {editing && <div className="admin-modal-backdrop" onMouseDown={() => setEditing(null)}><form className="admin-modal" onSubmit={submit} onMouseDown={(e) => e.stopPropagation()}><div className="admin-modal__head"><div><p className="admin-kicker">PORTADA</p><h2>{editing.id ? "Editar banner" : "Nuevo banner"}</h2></div><button type="button" onClick={() => setEditing(null)}>×</button></div><div className="admin-form-grid"><label className="wide">Texto superior<input required value={editing.eyebrow} onChange={(e) => setEditing({ ...editing, eyebrow: e.target.value })} /></label><label className="wide">Título<input required value={editing.title} onChange={(e) => setEditing({ ...editing, title: e.target.value })} /></label><label className="wide">Descripción<textarea rows="3" value={editing.description} onChange={(e) => setEditing({ ...editing, description: e.target.value })} /></label><label>Botón<input value={editing.cta} onChange={(e) => setEditing({ ...editing, cta: e.target.value })} /></label><label>Ruta<input value={editing.path} onChange={(e) => setEditing({ ...editing, path: e.target.value })} /></label><label className="wide">Imagen<input type="file" accept="image/*" onChange={(e) => readImage(e.target.files[0])} /></label>{editing.image && <img className="admin-image-preview wide" src={editing.image} alt="Vista previa" />}</div><div className="admin-modal__actions"><button type="button" className="admin-button admin-button--secondary" onClick={() => setEditing(null)}>Cancelar</button><button className="admin-button">Guardar banner</button></div></form></div>}
  </section>;
}
