import { useMemo, useState } from "react";
import { useAdmin } from "../context/AdminContext";

const emptyProduct = { name: "", price: "", category: "cleaning", type: "", image: "", description: "" };

export default function Productos() {
  const { products, saveProduct, deleteProduct } = useAdmin();
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("all");
  const [editing, setEditing] = useState(null);
  const filtered = useMemo(() => products.filter((product) => (category === "all" || product.category === category) && product.name.toLowerCase().includes(search.toLowerCase())), [products, search, category]);
  const submit = (event) => { event.preventDefault(); saveProduct({ ...editing, price: Number(editing.price) }); setEditing(null); };
  const readImage = (file) => { if (!file) return; const reader = new FileReader(); reader.onload = () => setEditing((current) => ({ ...current, image: reader.result })); reader.readAsDataURL(file); };

  return <section className="admin-page"><header className="admin-page__header"><div><p className="admin-kicker">CATÁLOGO</p><h1>Productos</h1><p>Administra productos, categorías, precios e imágenes.</p></div><button className="admin-button" onClick={() => setEditing(emptyProduct)}>＋ Nuevo producto</button></header>
    <div className="admin-toolbar"><label className="admin-search">⌕<input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar productos..." /></label><select value={category} onChange={(e) => setCategory(e.target.value)}><option value="all">Todas las categorías</option><option value="cleaning">Limpieza</option><option value="bookshop">Librería</option><option value="desktop">Escritorio</option></select><span className="admin-count">{filtered.length} productos</span></div>
    <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Producto</th><th>Categoría</th><th>Tipo</th><th>Precio</th><th></th></tr></thead><tbody>{filtered.map((product) => <tr key={`${product.category}-${product.id}`}><td><div className="admin-product"><img src={product.image} alt="" /><div><strong>{product.name}</strong><small>#{product.id}</small></div></div></td><td><span className="admin-chip">{product.category}</span></td><td>{product.type}</td><td><strong>${Number(product.price).toLocaleString("es-CL")}</strong></td><td><div className="admin-row-actions"><button onClick={() => setEditing({ ...product })}>Editar</button><button className="danger" onClick={() => window.confirm("¿Eliminar este producto?") && deleteProduct(product)}>Eliminar</button></div></td></tr>)}</tbody></table>{!filtered.length && <div className="admin-empty">No se encontraron productos.</div>}</div>
    {editing && <div className="admin-modal-backdrop" onMouseDown={() => setEditing(null)}><form className="admin-modal" onSubmit={submit} onMouseDown={(e) => e.stopPropagation()}><div className="admin-modal__head"><div><p className="admin-kicker">PRODUCTO</p><h2>{editing.id ? "Editar producto" : "Nuevo producto"}</h2></div><button type="button" onClick={() => setEditing(null)}>×</button></div><div className="admin-form-grid"><label className="wide">Nombre<input required value={editing.name} onChange={(e) => setEditing({ ...editing, name: e.target.value })} /></label><label>Precio<input required min="0" type="number" value={editing.price} onChange={(e) => setEditing({ ...editing, price: e.target.value })} /></label><label>Categoría<select value={editing.category} onChange={(e) => setEditing({ ...editing, category: e.target.value })}><option value="cleaning">Limpieza</option><option value="bookshop">Librería</option><option value="desktop">Escritorio</option></select></label><label className="wide">Tipo<input required value={editing.type} onChange={(e) => setEditing({ ...editing, type: e.target.value })} /></label><label className="wide">Descripción<textarea rows="4" value={editing.description} onChange={(e) => setEditing({ ...editing, description: e.target.value })} /></label><label className="wide">Imagen<input type="file" accept="image/*" onChange={(e) => readImage(e.target.files[0])} /></label>{editing.image && <img className="admin-image-preview wide" src={editing.image} alt="Vista previa" />}</div><div className="admin-modal__actions"><button type="button" className="admin-button admin-button--secondary" onClick={() => setEditing(null)}>Cancelar</button><button className="admin-button">Guardar producto</button></div></form></div>}
  </section>;
}
